/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        headline: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        label: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
      },
      colors: {
        "inverse-primary":                "rgba(var(--color-inverse-primary) / <alpha-value>)",
        "primary-fixed-dim":              "rgba(var(--color-primary-fixed-dim) / <alpha-value>)",
        "on-tertiary-container":          "rgba(var(--color-on-tertiary-container) / <alpha-value>)",
        "secondary-fixed-dim":            "rgba(var(--color-secondary-fixed-dim) / <alpha-value>)",
        "inverse-on-surface":             "rgba(var(--color-inverse-on-surface) / <alpha-value>)",
        "on-tertiary":                    "rgba(var(--color-on-tertiary) / <alpha-value>)",
        "secondary-container":            "rgba(var(--color-secondary-container) / <alpha-value>)",
        "outline":                        "rgba(var(--color-outline) / <alpha-value>)",
        "on-tertiary-fixed":              "rgba(var(--color-on-tertiary-fixed) / <alpha-value>)",
        "surface-container-high":         "rgba(var(--color-surface-container-high) / <alpha-value>)",
        "primary":                        "rgba(var(--color-primary) / <alpha-value>)",
        "tertiary-fixed":                 "rgba(var(--color-tertiary-fixed) / <alpha-value>)",
        "on-surface":                     "rgba(var(--color-on-surface) / <alpha-value>)",
        "on-secondary":                   "rgba(var(--color-on-secondary) / <alpha-value>)",
        "on-secondary-fixed-variant":     "rgba(var(--color-on-secondary-fixed-variant) / <alpha-value>)",
        "on-primary":                     "rgba(var(--color-on-primary) / <alpha-value>)",
        "on-error-container":             "rgba(var(--color-on-error-container) / <alpha-value>)",
        "surface-bright":                 "rgba(var(--color-surface-bright) / <alpha-value>)",
        "on-background":                  "rgba(var(--color-on-background) / <alpha-value>)",
        "surface":                        "rgba(var(--color-surface) / <alpha-value>)",
        "on-secondary-container":         "rgba(var(--color-on-secondary-container) / <alpha-value>)",
        "secondary-fixed":                "rgba(var(--color-secondary-fixed) / <alpha-value>)",
        "surface-container":              "rgba(var(--color-surface-container) / <alpha-value>)",
        "outline-variant":                "rgba(var(--color-outline-variant) / <alpha-value>)",
        "on-surface-variant":             "rgba(var(--color-on-surface-variant) / <alpha-value>)",
        "on-error":                       "rgba(var(--color-on-error) / <alpha-value>)",
        "surface-container-low":          "rgba(var(--color-surface-container-low) / <alpha-value>)",
        "error":                          "rgba(var(--color-error) / <alpha-value>)",
        "on-primary-fixed-variant":       "rgba(var(--color-on-primary-fixed-variant) / <alpha-value>)",
        "on-primary-container":           "rgba(var(--color-on-primary-container) / <alpha-value>)",
        "inverse-surface":                "rgba(var(--color-inverse-surface) / <alpha-value>)",
        "on-tertiary-fixed-variant":      "rgba(var(--color-on-tertiary-fixed-variant) / <alpha-value>)",
        "surface-dim":                    "rgba(var(--color-surface-dim) / <alpha-value>)",
        "background":                     "rgba(var(--color-background) / <alpha-value>)",
        "surface-variant":                "rgba(var(--color-surface-variant) / <alpha-value>)",
        "tertiary-fixed-dim":             "rgba(var(--color-tertiary-fixed-dim) / <alpha-value>)",
        "surface-container-lowest":       "rgba(var(--color-surface-container-lowest) / <alpha-value>)",
        "on-secondary-fixed":             "rgba(var(--color-on-secondary-fixed) / <alpha-value>)",
        "tertiary":                       "rgba(var(--color-tertiary) / <alpha-value>)",
        "primary-fixed":                  "rgba(var(--color-primary-fixed) / <alpha-value>)",
        "surface-container-highest":      "rgba(var(--color-surface-container-highest) / <alpha-value>)",
        "error-container":                "rgba(var(--color-error-container) / <alpha-value>)",
        "surface-tint":                   "rgba(var(--color-surface-tint) / <alpha-value>)",
        "secondary":                      "rgba(var(--color-secondary) / <alpha-value>)",
        "primary-container":              "rgba(var(--color-primary-container) / <alpha-value>)",
        "tertiary-container":             "rgba(var(--color-tertiary-container) / <alpha-value>)",
        "on-primary-fixed":               "rgba(var(--color-on-primary-fixed) / <alpha-value>)",
      },
      keyframes: {
        fadeUp: {
          '0%':   { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideInLeft: {
          '0%':   { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
      animation: {
        'fade-up':    'fadeUp 0.45s cubic-bezier(0.16, 1, 0.3, 1) both',
        'fade-in':    'fadeIn 0.3s ease-out both',
        'slide-left': 'slideInLeft 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
      },
      boxShadow: {
        'premium':     '0 1px 3px rgba(0,0,0,0.4), 0 8px 32px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.05)',
        'premium-lg':  '0 2px 8px rgba(0,0,0,0.5), 0 16px 48px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.08)',
        'glow-indigo': '0 0 24px rgba(130,131,255,0.25)',
        'glow-mint':   '0 0 24px rgba(78,222,163,0.2)',
      },
      backdropBlur: {
        'glass': '20px',
      },
      transitionDuration: {
        '200': '200ms',
      },
    },
  },
  plugins: [],
}
