/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#00311f",
        "error-container": "#93000a",
        "secondary-fixed": "#6ffbbe",
        "error": "#ffb4ab",
        "surface-container-low": "#131b2e",
        "on-error": "#690005",
        "surface": "#0b1326",
        "tertiary": "#ffb783",
        "secondary-container": "#00a572",
        "on-secondary": "#003824",
        "secondary": "#4edea3",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-container": "#0d0096",
        "inverse-primary": "#494bd6",
        "outline": "#908fa0",
        "outline-variant": "#464554",
        "surface-container-highest": "#2d3449",
        "on-surface-variant": "#c7c4d7",
        "on-primary": "#1000a9",
        "surface-container-lowest": "#060e20",
        "on-primary-fixed": "#07006c",
        "inverse-on-surface": "#283044",
        "secondary-fixed-dim": "#4edea3",
        "tertiary-container": "#d97721",
        "surface-tint": "#c0c1ff",
        "on-tertiary": "#4f2500",
        "surface-bright": "#31394d",
        "on-tertiary-container": "#452000",
        "primary-container": "#8083ff",
        "on-surface": "#dae2fd",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container-high": "#222a3d",
        "inverse-surface": "#dae2fd",
        "tertiary-fixed": "#ffdcc5",
        "surface-container": "#171f33",
        "on-secondary-fixed": "#002113",
        "surface-dim": "#0b1326",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb783",
        "on-secondary-fixed-variant": "#005236",
        "surface-variant": "#2d3449",
        "primary-fixed": "#e1e0ff",
        "on-background": "#dae2fd",
        "primary": "#c0c1ff",
        "background": "#0b1326",
        "on-tertiary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#703700"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
